/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DetailsPropertyIdImport } from './routes/details.$propertyId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DetailsPropertyIdRoute = DetailsPropertyIdImport.update({
  id: '/details/$propertyId',
  path: '/details/$propertyId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/details/$propertyId': {
      id: '/details/$propertyId'
      path: '/details/$propertyId'
      fullPath: '/details/$propertyId'
      preLoaderRoute: typeof DetailsPropertyIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/details/$propertyId': typeof DetailsPropertyIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/details/$propertyId': typeof DetailsPropertyIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/details/$propertyId': typeof DetailsPropertyIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/details/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/details/$propertyId'
  id: '__root__' | '/' | '/details/$propertyId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DetailsPropertyIdRoute: typeof DetailsPropertyIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DetailsPropertyIdRoute: DetailsPropertyIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/details/$propertyId"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/details/$propertyId": {
      "filePath": "details.$propertyId.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
